export type LangType = 'KO' | 'EN';

export const LANG_DICT: Record<LangType, Record<string, string>> = {
  KO: {
    title: 'ClassFit | 가천대학교 강의실 예약 시스템',
    subtitle: 'Gachon University Classroom Reservation System',
    footer: '© 2026 가천대학교 학사의사결정지원처 ClassFit. All Rights Reserved.',
    
    // 로그인
    loginCardTitle: '가천대학교 통합 로그인',
    loginCardDesc: '학번 또는 사번을 입력하여 로그인해 주세요.',
    userIdLabel: '아이디 (학번 / 사번)',
    userIdPlaceholder: '학번(9자리), 사번(7자리) 또는 "admin" 입력',
    loginButton: '로그인',
    loginError: '올바르지 않은 계정 정보입니다. 학번은 9자리, 사번은 7자리 숫자여야 하며 관리자는 "admin"입니다.',
    loginSuccessStudent: '학생 계정으로 로그인되었습니다.',
    loginSuccessProfessor: '교수 계정으로 로그인되었습니다.',
    loginSuccessAdmin: '관리자 계정으로 로그인되었습니다.',
    logoutButton: '로그아웃',
    
    // 역할
    roleStudent: '학생',
    roleProfessor: '교수',
    roleAdmin: '관리자',
    welcomeUser: '님, 환영합니다.',
    
    // 언어 설정
    langSelectLabel: '언어 설정',
    
    // 공통 속성
    building: '건물명',
    roomNumber: '강의실 번호',
    capacity: '수용 정원',
    equipment: '보유 기자재',
    peopleUnit: '명',
    periods: '교시',
    date: '날짜',
    purpose: '이용 목적',
    
    // 사이드바 및 메뉴
    menuSearch: '강의실 조회 및 예약',
    menuMyReservations: '내 예약 내역 확인',
    menuAdminDashboard: '실시간 가용 현황판',
    menuRoomManagement: '강의실 데이터 관리',
    menuStatistics: '강의실 이용 통계',
    menuSystemControl: '인프라 관리 센터',
    
    // 검색 화면
    searchTitle: '조건별 맞춤 강의실 검색',
    searchDesc: '다중 필터링 및 고속 정렬 시스템 (연결 리스트 & 퀵 정렬)',
    filterAll: '전체 건물',
    filterBuilding: '건물 선택',
    filterCapacity: '최소 수용 인원',
    filterEquipment: '필수 기자재',
    searchQueryPlaceholder: '강의실 번호, 고유 코드 또는 건물명으로 검색...',
    sortByLabel: '정렬 기준',
    sortAsc: '오름차순 정렬',
    sortDesc: '내림차순 정렬',
    roomListTitle: '검색 결과 강의실 목록',
    noRoomsFound: '선택하신 조건과 일치하는 강의실이 존재하지 않습니다.',
    
    // 예약 화면 및 폼
    roomDetails: '강의실 상세 정보 및 예약 신청',
    reserveBtn: '예약 신청',
    reserveInputDate: '예약 일자',
    reserveInputPeriods: '이용 교시 선택 (복수 선택 가능)',
    reserveInputPurpose: '이용 목적 및 상세 사유',
    reserveInputPurposePlaceholder: '예: 전공 보충 스터디, 프로젝트 회의 등',
    reserveSuccess: '강의실 예약이 완료되었습니다. (해시맵 트랜잭션 기록 완료)',
    reserveConflictTitle: '⚠️ 예약 시간대 충돌 감지',
    reserveConflictDesc: '선택하신 날짜와 교시에 이미 등록된 예약이 있습니다. (이진 탐색 충돌 검증 완료)',
    recommendTitle: '💡 클래스핏 맞춤 대체 강의실 추천',
    recommendDesc: '최단 경로 탐색 알고리즘을 통해 현재 시간대에 이용 가능한 가장 가까운 대체 강의실을 찾은 결과입니다.',
    recommendBookBtn: '추천 강의실로 예약하기',
    recommendEmpty: '해당 시간대에 추천할 만한 대체 강의실이 근거리에 남아있지 않습니다.',
    
    // 이력 관리 (Undo / Redo)
    historyHeader: '작업 이력 관리',
    historyDesc: '가장 최근의 예약을 취소하거나 다시 실행합니다.',
    undoBtn: '실행 취소',
    redoBtn: '다시 실행',
    stackState: '작업 이력 스택 상태',
    undoCount: '실행 취소 가능 횟수',
    redoCount: '다시 실행 가능 횟수',
    undoSuccess: '직전 작업이 성공적으로 취소되었습니다.',
    redoSuccess: '취소했던 작업이 정상적으로 복구되었습니다.',
    noUndo: '실행 취소할 기록이 없습니다.',
    noRedo: '다시 실행할 기록이 없습니다.',
    
    // 내 예약 확인
    myResTitle: '내 예약 현황',
    myResCount: '건의 활성화된 예약 내역이 있습니다.',
    resTableCode: '예약 번호',
    resTableRoom: '강의실',
    resTableDate: '예약 날짜',
    resTablePeriods: '이용 교시',
    resTablePurpose: '이용 목적',
    resTableAction: '예약 취소',
    resCancelConfirm: '해당 예약을 취소하시겠습니까?',
    resCancelSuccess: '예약이 성공적으로 취소되었습니다.',
    noMyReservations: '현재 계정으로 등록된 예약 내역이 없습니다.',
    
    // 관리자 현황판 (Admin Dashboard)
    adminDashTitle: '종합 공간 가용 현황실',
    adminDashDesc: '연속 공강 매칭 탐색을 통해 연속 공강 시간이 긴 강의실을 탐색하고, 우선순위 지수 기준으로 정렬합니다.',
    windowSizeLabel: '최소 연속 공강 시간 설정 (교시 단위)',
    windowSizeDesc: '입력한 교시만큼 연속으로 비어 있는 여유 강의실을 판정합니다.',
    emptySlotsHeader: '연속 공강 강의실 보고서',
    colRoom: '강의실 ID',
    colBuilding: '건물명',
    colMaxCapacity: '최대 수용 정원',
    colLongestStreak: '최대 연속 공강',
    colWindowStreak: '이용 가능 교시 범위',
    colPriorityScore: '우선순위 지수',
    colStatus: '실시간 가용 상황',
    allRoomsFull: '조건을 충족하는 빈 강의실이 존재하지 않습니다.',
    
    // 관리자 자산 관리 (Admin Room Management CRUD)
    roomMgmtTitle: '강의 시설 관리 대장',
    roomMgmtDesc: '교내 강의실 정보를 새로 등록하거나, 기존 정보를 수정 및 삭제할 수 있습니다.',
    addRoomBtn: '강의실 추가',
    editRoomBtn: '정보 수정',
    deleteRoomBtn: '강의실 삭제',
    inputId: '강의실 고유 ID',
    inputIdPlaceholder: '예시: IT-401',
    inputNumber: '강의실 번호',
    inputNumberPlaceholder: '예시: 401',
    inputBuilding: '건물명',
    inputBuildingPlaceholder: '예시: IT융합대학',
    inputCapacity: '수용 정원 제한',
    inputEquipment: '설치 기자재 (쉼표로 구분하여 작성)',
    inputEquipmentPlaceholder: '예시: 빔 프로젝터, 화이트보드, PC 실습장비',
    inputNearby: '인접 강의실 ID 목록 (대체 추천용, 쉼표 구분)',
    inputNearbyPlaceholder: 'IT-402, IT-403',
    inputPriority: '기본 우선순위 가중치 (1~10 범위)',
    crudAddSuccess: '신규 강의실 정보가 성공적으로 등록되었습니다.',
    crudUpdateSuccess: '강의실 정보 수정 사항이 데이터베이스에 반영되었습니다.',
    crudDeleteSuccess: '해당 강의실 정보가 성공적으로 삭제되었습니다.',
    confirmDelete: '이 강의실을 영구 삭제하시겠습니까? 관련 수업 시간표 및 예약 내역이 함께 삭제됩니다.',
    
    // 통계
    statsTitle: '강의실 이용 누적 통계 분석',
    statsDesc: '수집된 예약 로그를 집계 데이터로 가공 산출한 통계 분석 리포트입니다.',
    statsTotalRes: '누적 총 예약 건수',
    statsTopRoom: '가장 이용 빈도가 높은 강의실',
    statsActiveUsers: '누적 이용자 수(고유 계정 수)',
    chartTitleResByRoom: '강의실별 누적 예약 점유수',
    chartTitleByBuilding: '단과대/건물별 강의실 점유 비율',
    noStatsData: '누적된 예약 데이터가 부족하여 통계 그래프를 표시할 수 없습니다.',
    
    // 시스템 제어
    infraTitle: '시스템 인프라 관리 센터',
    infraDesc: '마스터 구조 백업본 로드, 원천 데이터 재동기화 및 학내 예약 기록 초기화',
    btnRestoreDb: '마스터 데이터 동기화 및 데이터베이스 초기화',
    btnPurgeDb: '실시간 예약 내역 전체 초기화',
    infraResetSuccess: '강의실 구성을 데이터베이스에 성공적으로 동기화했으며, 대체 추천 그래프 구조를 갱신했습니다.',
    infraPurgeSuccess: '데이터 무결성을 유지하며 전체 예약 내역을 안전하게 일괄 삭제했습니다.',
    
    // 가천대 건물 이름
    buildingAI: 'IT융합대학 (AI공학관)',
    buildingGlobal: '글로벌센터',
    buildingEngineering: '공과대학 본관',
    buildingArts: '예술체육대학',
    
    // 교수 전용 기능
    menuProfessorView: '교수 전용 포털',
    menuVacantFinder: '유휴 강의실 연속 공강 조회',
    menuAcademicSchedule: '학과별 정규 주간 시간표',
    vacantFinderDesc: '연속 공강 시간 탐색 기법을 가동하여 특정 시간 이상의 공석을 확인하고, 우선순위 계산을 통해 순위별 정렬을 수행합니다.',
    btnFindVacant: '연속 공강 빈 방 조회',
    academicScheduleDesc: '학과별 주간 정규 수업 편성 계획표이며, 해당 시간대에는 일반 예약이 자동으로 차단됩니다.',
    colSemester: '학기 구분',
    colCourseName: '교과목명',
    colProfessor: '담당 교수(사번)',
  },
  EN: {
    title: 'ClassFit | Gachon University Integrated Reservation System',
    subtitle: 'Gachon University Classroom Reservation System',
    footer: '© 2026 Gachon University Academic Center ClassFit. All Rights Reserved.',
    
    // Login
    loginCardTitle: 'Gachon University Integrated Log-in',
    loginCardDesc: 'Please enter your unique Student ID or Staff ID to authenticate.',
    userIdLabel: 'User ID (Student ID / Staff ID)',
    userIdPlaceholder: 'Enter Student ID (9 digits) or Staff ID (7 digits, "admin")',
    loginButton: 'Sign In',
    loginError: 'Invalid account credentials. Student ID must be 9 digits, Staff ID must be 7 digits, or use "admin" for administrators.',
    loginSuccessStudent: 'Successfully logged in with Student privileges.',
    loginSuccessProfessor: 'Successfully logged in with Professor privileges.',
    loginSuccessAdmin: 'Successfully logged in with Administrator privileges.',
    logoutButton: 'Sign Out',
    
    // Roles
    roleStudent: 'Student',
    roleProfessor: 'Professor',
    roleAdmin: 'Administrator (Staff)',
    welcomeUser: ', Welcome back.',
    
    // Switch Language
    langSelectLabel: 'Language Settings',
    
    // Common Room attributes
    building: 'Building Name',
    roomNumber: 'Room Number',
    capacity: 'Capacity Limit',
    equipment: 'Amenities & Equipment',
    peopleUnit: 'persons',
    periods: 'Periods',
    date: 'Date',
    purpose: 'Purpose of Use',
    
    // Sidebar & Menus
    menuSearch: 'Search & Book Classrooms',
    menuMyReservations: 'My Reservation Records',
    menuAdminDashboard: 'Real-Time Availability Dashboard',
    menuRoomManagement: 'Classroom Asset Registry',
    menuStatistics: 'Usage Analytics & Statistics',
    menuSystemControl: 'Backend Infrastructure Control',
    
    // Search View
    searchTitle: 'Find Classrooms by Criteria',
    searchDesc: 'Multi-criteria filtering and high-speed sorting engine (Powered by Linked List & Quick Sort structures)',
    filterAll: 'All Buildings',
    filterBuilding: 'Select Building',
    filterCapacity: 'Minimum Capacity',
    filterEquipment: 'Required Equipment',
    searchQueryPlaceholder: 'Search by room number, code, or building name...',
    sortByLabel: 'Sort By',
    sortAsc: 'Ascending Order',
    sortDesc: 'Descending Order',
    roomListTitle: 'Matching Classrooms',
    noRoomsFound: 'No classrooms matching the specified criteria were found on campus.',
    
    // Reservation View & Form
    roomDetails: 'Classroom Details & Booking Request',
    reserveBtn: 'Submit Reservation',
    reserveInputDate: 'Target Date',
    reserveInputPeriods: 'Select Period Slots (Multiple Selections Allowed)',
    reserveInputPurpose: 'Purpose of Use & Description',
    reserveInputPurposePlaceholder: 'e.g., Study group for exams, Project development seminar, etc.',
    reserveSuccess: 'Reservation completed successfully. (Transaction committed securely via Hash Map cache)',
    reserveConflictTitle: '⚠️ Schedule Conflict Detected',
    reserveConflictDesc: 'The selected date and time slots are already booked. (Conflict verified via Binary Search conflict algorithm)',
    recommendTitle: '💡 ClassFit Smart Alternative Recommendation',
    recommendDesc: 'Using the Breadth-First Search (BFS) algorithm, we have automatically found the closest available alternative classroom for your requested time.',
    recommendBookBtn: 'Switch to Recommended Room Instantly',
    recommendEmpty: 'No unoccupied alternative classrooms are available close to this location at your requested time.',

    // History Controller (Undo / Redo)
    historyHeader: 'Operation History Stack Control (Undo / Redo)',
    historyDesc: 'Manage active state workflows securely with LIFO stacks (History Stack Engine)',
    undoBtn: 'Undo Last Action',
    redoBtn: 'Restore Undone Actions (Redo)',
    stackState: 'History Manager Stack Status',
    undoCount: 'Available Un-dos',
    redoCount: 'Available Re-dos',
    undoSuccess: 'Your previous booking action has been rolled back successfully.',
    redoSuccess: 'Your undone booking records have been restored successfully.',
    noUndo: 'No actions left to undo.',
    noRedo: 'No actions left to redo.',
    
    // My Reservations
    myResTitle: 'My Live Bookings Dashboard',
    myResCount: 'active classroom reservations exist under this account.',
    resTableCode: 'Booking Ref #',
    resTableRoom: 'Venue',
    resTableDate: 'Reserved Date',
    resTablePeriods: 'Reserved Periods',
    resTablePurpose: 'Purpose & Description',
    resTableAction: 'Cancel Booking',
    resCancelConfirm: 'Are you absolutely sure you want to cancel this reservation and revoke structural access?',
    resCancelSuccess: 'The selected reservation has been permanently purged and canceled from the system.',
    noMyReservations: 'No upcoming reservation records exist under these credentials.',

    // Admin Dashboard (Sliding Window & Priority Queue)
    adminDashTitle: 'Comprehensive Workspace Availability Monitor',
    adminDashDesc: 'Scans continuous vacant period sizes via the Sliding Window algorithm, sorted by high structural asset priority (Priority Queue weights).',
    windowSizeLabel: 'Min. Continuous Free Time Slots (Periods)',
    windowSizeDesc: 'Sliding Window filters classrooms having at least this number of consecutive free periods.',
    emptySlotsHeader: 'Classrooms with Continuous Idle Slots (Priority Queue Sorted)',
    colRoom: 'Classroom ID',
    colBuilding: 'Building Category',
    colMaxCapacity: 'Max Capacity',
    colLongestStreak: 'Max Continuous Idle Slots',
    colWindowStreak: 'Compliant Idle Slots Range',
    colPriorityScore: 'Priority Score',
    colStatus: 'Real-Time Status',
    allRoomsFull: 'No classrooms currently satisfy the given Sliding Window consecutive slot criteria.',

    // Admin Room Management CRUD
    roomMgmtTitle: 'Integrated Campus Asset Registry (CRUD Dashboard)',
    roomMgmtDesc: 'Register new classrooms, update structural specification schemas, or permanently decommission legacy assets instantly.',
    addRoomBtn: 'Register New Classroom',
    editRoomBtn: 'Update Room Specifications',
    deleteRoomBtn: 'Decommission Room Asset',
    inputId: 'Classroom Unique ID',
    inputIdPlaceholder: 'e.g., IT-401',
    inputNumber: 'Room Number',
    inputNumberPlaceholder: 'e.g., 401',
    inputBuilding: 'Building Category',
    inputBuildingPlaceholder: 'e.g., AI Building',
    inputCapacity: 'Approved Capacity Limit',
    inputEquipment: 'Equipped Hardware (comma-separated list)',
    inputEquipmentPlaceholder: 'e.g., Projector, Whiteboard, PC Lab',
    inputNearby: 'Adjacent Classrooms (for BFS recommendation, comma-separated)',
    inputNearbyPlaceholder: 'IT-402, IT-403',
    inputPriority: 'Weight Assignment Rank (Range 1~10)',
    crudAddSuccess: 'New classroom asset successfully configured in system master records.',
    crudUpdateSuccess: 'Room properties revised and instantly serialized in local database.',
    crudDeleteSuccess: 'Classroom decommissioning completed. Record permanently purged from system files.',
    confirmDelete: 'Are you sure you want to delete this room entirely? Future scheduling metrics linked to this asset will be permanently lost.',

    // Statistics
    statsTitle: 'Campus Workspace Usage Analytics & Forecasting',
    statsDesc: 'Statistical infographics report showing analytical metrics processed via highly optimized SQL GROUP BY query models.',
    statsTotalRes: 'Total Accumulated Bookings',
    statsTopRoom: 'Most Heavily Booked Workspace',
    statsActiveUsers: 'Total Unique Active Users',
    chartTitleResByRoom: 'Cumulative Reservations Booked by Classroom ID',
    chartTitleByBuilding: 'Booking Occupancy Share Split by Department Category',
    noStatsData: 'Insufficient scheduling telemetry registered to compute visual metrics charts.',

    // Infrastructure Controls
    infraTitle: 'Backend Infrastructure Maintenance Controller',
    infraDesc: 'Maintain database synchronization, rebuild indices, and reload campus baseline CSV registries.',
    btnRestoreDb: 'Synchronize Master CSV Records & Reset Database',
    btnPurgeDb: 'Purge Active Scheduling Reservations Securely',
    infraResetSuccess: 'Classroom master records successfully seeded from CSV files. BFS node networks fully re-constructed.',
    infraPurgeSuccess: 'All active booking records erased. System returned to default vacant state.',
    
    // Gachon Campus Buildings Custom Labels
    buildingAI: 'IT융합대학 (AI공학관) / AI Building',
    buildingGlobal: '글로벌센터 (대학본부) / Global Center',
    buildingEngineering: '공과대학 본관동 / College of Engineering',
    buildingArts: '예술체육대학 강의동 / Arts and Design Building',
    
    // Professor View specific
    menuProfessorView: 'Gachon University Professor Portal',
    menuVacantFinder: 'Continuous Vacant Slots Finder (Sliding Window)',
    menuAcademicSchedule: 'Fixed Department Lecture Timetable',
    vacantFinderDesc: 'Runs a Sliding Window query to find continuous unoccupied period streams, sorted by high structural asset priority (Priority Queue weights).',
    btnFindVacant: 'Search Continuous Vacant Rooms',
    academicScheduleDesc: 'Baseline fixed academic timetables assigned to your department that automatically block slots from regular reservations.',
    colSemester: 'Semester Term',
    colCourseName: 'Course Title',
    colProfessor: 'Instructor (Staff ID)',
  }
};
